
GET http://localhost:8000/health

###
POST http://localhost:8000/api/v1/notifications
Content-Type: application/json

{
  "type": "email",
  "recipient": "user@example.com",
  "message": "hello from http file"
}

###
POST http://localhost:8000/api/v1/notifications
Content-Type: application/json

{
  "type": "email",
  "recipient": "bad-email",
  "message": "hello"
}

###
POST http://localhost:8000/api/v1/notifications
Content-Type: application/json

{
  "type": "email",
  "recipient": "user@example.com",
  "subject": "Подтвердите регистрацию",
  "message": "Перейдите по ссылке для подтверждения."
}

###
POST http://localhost:8000/api/v1/notifications
Content-Type: application/json

{
  "type": "email",
  "recipient": "user@example.com",
  "subject": "Welcome",
  "message": "Hello!",
  "channel_data": {
    "template_id": "welcome_v1",
    "from_name": "Test"
  }
}

### 
GET http://localhost:8000/api/v1/notifications/<id>